# Generated by Django 4.1.7 on 2023-07-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_cars_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
